

spring.application.name=expense-tracker

spring.datasource.url=jdbc:mysql://mysql-1c63a36a-bintasrari-0403.i.aivencloud.com:17118/expensetrackerdb
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_CYfhtlsOQiuDmg94amB

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.thymeleaf.cache=false
